version: '3.2'
services:
  #glpk:
  #  build:
  #    context: ""
  #    dockerfile: docker/Glpk/Dockerfile
  #  image: glpk
  #  #command: /bin/bash
  #  restart: always
  #  #command: ["cat","/etc/ld.so.conf"]
  #  volumes:
  #    - volume-glpsol:/usr/local/bin
  #    #- volume-glpsol:/user/local/glpk-4.57
  #    - volume-glpk:/usr/local/lib
      #- /var/run/docker.sock:/docker.sock
    #pid: host
    #environment:
    #    - run_mode=batch,daemon
    #    - host_routes=true
    #    - route_add_delay=1
     # - /usr/src/app:/usr/src/app/glpk
      #- type: bind
      #  source: /usr/src/app/glpk
      #  target: /usr/bin/glpsol
    #restart: unless-stopped

  #ipopt:
    #build:
      #context: ""
      #dockerfile: docker/Ipopt/Dockerfile
    #image: garagon/ipopt:V0.2
 # bonmin:
 #   build:
 #     context: ""
 #     dockerfile: docker/Bonmin/Dockerfile
 #   image: garagon/bonmin:V0.1
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    container_name: "mosquito_S4G"

  redis:
    image: redis:latest
    container_name: "redis_S4G"
    command: redis-server
    ports:
      - "6379:6379"
  ofw:
    build:
      context: ""
      dockerfile: Dockerfile
     # ../docker/App/Dockerfile
    image: myapp-ofw-ipopt
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes:
      - ../optimization-framework/prediction/resources:/usr/src/app/res
    command: ["python3", "-u", "ofw.py"]

  mock:
    build:
      context: ""
      dockerfile: mock_data/docker-arm/Dockerfile-mock
    command: ["python3", "-u", "mockdata.py", "ESS_Control~l:24~v:0", "SoC_Value" , "P_Load", "Q_Load"]
  ml:
    build:
      context: ""
      dockerfile: prediction/docker/Dockerfile
    depends_on:
      - redis
    volumes:
      - ../optimization-framework/prediction/resources:/usr/src/app/res
    command: ["python3", "-u", "mlTraining.py"]

  connector:
    build:
      context: ""
      dockerfile: connector/docker/Dockerfile
    volumes:
      - ../optimization-framework/connector/resources/:/usr/src/app/connector/resources
    command: ["python3", "-u", "connectors.py"]

