version: "3.2"
services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    container_name: "mosquito_S4G"
  redis:
    image: redis:latest
    container_name: "redis_S4G"
    command: redis-server
    ports:
      - "6379:6379"
  ofw:
    build:
      context: ""
      dockerfile: Dockerfile
    image: ofw-solvers
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ../optimization-framework/prediction/resources:/usr/src/app/prediction/resources
      - ../optimization-framework/optimization/resources:/usr/src/app/optimization/resources
      - ../optimization-framework/utils/resources:/usr/src/app/utils/resources
      - ../optimization-framework/logs:/usr/src/app/logs
      - ../optimization-framework/utils/gurobi/license:/usr/src/app/share/gurobi811/license
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    command: ["python3", "-u", "ofw.py"]
  mock:
    build:
      context: ""
      dockerfile: mock_data/docker/Dockerfile-mock
    volumes:
      - ../optimization-framework/mock_data/resources:/usr/src/app/mock_data/resources
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    command: ["python3", "-u", "mockdata.py"]
  ml:
    build:
      context: ""
      dockerfile: prediction/docker/Dockerfile
    depends_on:
      - redis
    volumes:
      - ../optimization-framework/prediction/resources:/usr/src/app/prediction/resources
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    command: ["python3", "-u", "mlTraining.py"]
  connector:
    build:
      context: ""
      dockerfile: connector/docker/Dockerfile
    volumes:
      - ../optimization-framework/connector/resources:/usr/src/app/connector/resources
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    command: ["python3", "-u", "connectors.py"]
